# Generated by Django 5.2.5 on 2025-08-16 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='URL 내 고유 코드', max_length=32, unique=True)),
                ('kind', models.CharField(blank=True, max_length=32)),
                ('grade', models.CharField(blank=True, max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('homepage', models.URLField(blank=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('occupancy', models.PositiveIntegerField(blank=True, null=True)),
                ('waiting', models.PositiveIntegerField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, help_text='가능/불가능 등', max_length=16)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('raw_overview', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation_date', models.DateField(blank=True, null=True)),
                ('evaluation_type', models.CharField(blank=True, max_length=100)),
                ('total_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('scores', models.JSONField(blank=True, default=dict, help_text='세부 카테고리 점수')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.facility')),
            ],
            options={
                'ordering': ['-evaluation_date', 'facility'],
            },
        ),
        migrations.CreateModel(
            name='LocationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('transport', models.TextField(blank=True)),
                ('parking', models.TextField(blank=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_info', to='core.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NonCoveredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_covered_items', to='core.facility')),
            ],
            options={
                'ordering': ['facility', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.facility')),
            ],
            options={
                'ordering': ['facility', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_counts', to='core.facility')),
            ],
            options={
                'ordering': ['facility', 'role'],
                'unique_together': {('facility', 'role')},
            },
        ),
    ]
