# Generated by Django 5.2.5 on 2025-08-16 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noncovereditem',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='program',
            name='facility',
        ),
        migrations.AlterUniqueTogether(
            name='staffcount',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='staffcount',
            name='facility',
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['name'], 'verbose_name': '시설', 'verbose_name_plural': '시설'},
        ),
        migrations.AlterModelOptions(
            name='facilityevaluation',
            options={'verbose_name': '평가정보', 'verbose_name_plural': '평가정보'},
        ),
        migrations.RemoveField(
            model_name='facility',
            name='address',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='raw_overview',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='facilityevaluation',
            name='evaluation_date',
        ),
        migrations.RemoveField(
            model_name='facilityevaluation',
            name='evaluation_type',
        ),
        migrations.RemoveField(
            model_name='facilityevaluation',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='facilityevaluation',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='facilityevaluation',
            name='total_score',
        ),
        migrations.AddField(
            model_name='facilityevaluation',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facilityevaluation',
            name='title',
            field=models.CharField(default='평가정보', max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='availability',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='facility',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='정원'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='occupancy',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='현원'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='waiting',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='대기'),
        ),
        migrations.AlterField(
            model_name='facilityevaluation',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_items', to='core.facility'),
        ),
        migrations.CreateModel(
            name='FacilityBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='기본정보', max_length=100)),
                ('content', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_items', to='core.facility')),
            ],
            options={
                'verbose_name': '기본정보',
                'verbose_name_plural': '기본정보',
            },
        ),
        migrations.CreateModel(
            name='FacilityHomepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='홈페이지', max_length=100)),
                ('content', models.TextField(blank=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_info', to='core.facility')),
            ],
            options={
                'verbose_name': '홈페이지',
                'verbose_name_plural': '홈페이지',
            },
        ),
        migrations.CreateModel(
            name='FacilityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='위치', max_length=100)),
                ('content', models.TextField(blank=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_info_simple', to='core.facility')),
            ],
            options={
                'verbose_name': '위치',
                'verbose_name_plural': '위치',
            },
        ),
        migrations.CreateModel(
            name='FacilityNonCovered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='비급여 항목', max_length=100)),
                ('content', models.TextField(blank=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='noncovered_info', to='core.facility')),
            ],
            options={
                'verbose_name': '비급여 항목',
                'verbose_name_plural': '비급여 항목',
            },
        ),
        migrations.CreateModel(
            name='FacilityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='프로그램운영', max_length=100)),
                ('content', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='core.facility')),
            ],
            options={
                'verbose_name': '프로그램운영',
                'verbose_name_plural': '프로그램운영',
            },
        ),
        migrations.CreateModel(
            name='FacilityStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='인력현황', max_length=100)),
                ('content', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_items', to='core.facility')),
            ],
            options={
                'verbose_name': '인력현황',
                'verbose_name_plural': '인력현황',
            },
        ),
        migrations.DeleteModel(
            name='LocationInfo',
        ),
        migrations.DeleteModel(
            name='NonCoveredItem',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='StaffCount',
        ),
    ]
