# Generated by Django 5.2.5 on 2025-08-17 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_noncovereditem_facility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitylocation',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_items', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='facilitynoncovered',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noncovered_items', to='core.facility'),
        ),
    ]
